services:
  springboot-app:
    container_name: spring-app
    image: lvh139/springapp:v1
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - D:\Workspace\db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: spring-boot-project
      MYSQL_ROOT_PASSWORD: root

