services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - D:\Workspace\db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: spring-boot-project
      MYSQL_ROOT_PASSWORD: root

